FROM node:22.23.3-alpine@sha256:0a7108bf6c7bf5de370ffb1a3ed6be93d405b43ff159f681a8d18c0e2bc2e402

WORKDIR /usr/src/app

ENV NODE_ENV=production

RUN apk add --no-cache git
COPY . .
RUN npm ci --omit=dev

EXPOSE 4100
CMD [ "npx", "@graffiticode/api" ]
