// Descriptions for the attribute reference. gen-attribute-reference.mjs joins
// these to the registries in question-types.ts: the registries say which words
// exist, what they emit and which types take them; this file says what they
// mean. The generator fails on a word that is in one and not the other, so the
// reference cannot fall behind the language.
//
// `group` places a nested word under the member it belongs inside. Question-level
// attributes are found from `validAttributes` and need no group.
// `value` is what the author writes, in L0176 terms.

export const GROUPS = [
  ["question", "Question Attributes",
    "Written directly in a question's member list. Each question type accepts only " +
    "the attributes Learnosity documents for it; any other is a compile error " +
    "naming the ones it does take."],
  ["validation", "Validation Members",
    "Written inside `validation [ ... ]`, which emits the question's `validation` object."],
  ["answer", "Answer Members",
    "Written inside an answer set — `valid-response [ ... ]` or one entry of " +
    "`alt-responses [[ ... ] [ ... ]]` — and, for `clozeformula`, inside each scoring rule " +
    "of the answer's `value`."],
  ["rule-options", "Rule Options",
    "Written inside a `clozeformula` scoring rule's `options [ ... ]`. They are the only " +
    "words in the language that emit camelCase. None is checked against the rule's " +
    "`method`: Learnosity documents options per method but accepts, and sometimes " +
    "ignores, any of them on any method — see C2 in `conflict-resolution.md`."],
  ["ui-style", "Layout Members",
    "Written inside `ui-style [ ... ]`, which emits the question's `ui_style` object. " +
    "Which keys a widget honours is set by Learnosity per type; L0176 does not check them."],
  ["response-container", "Response Container Members",
    "Written inside `response-container [ ... ]` (every response box) or one entry of " +
    "`response-containers [[ ... ] [ ... ]]` (one box each, in order)."],
  ["structure", "Option and Group Members",
    "The members of the objects that make up a question's content: `mcq` options, " +
    "`bowtie` response groups, and `clozeformula` hints."],
  ["metadata", "Metadata Members",
    "Written inside `metadata [ ... ]`. At question level they emit the question's " +
    "`metadata` object. At item level the compiler routes each to where the Learnosity " +
    "Author Site reads it, as noted per word."],
  ["block", "Block and Custom Members",
    "Members of the `items` list and of the `custom` question type."],
];

export const DOCS = {
  // ---------------------------------------------------------------- question
  "case-sensitive": { value: "boolean",
    text: "Whether letter case counts when comparing the response with the answer. Learnosity's default is `false`. Prefer `case-sensitive false` to listing case variants as alternates." },
  "character-map": { value: "boolean or list of strings",
    text: "Shows a special-character button. `true` gives Learnosity's default set; a list shows exactly those characters." },
  "disable-auto-link": { value: "boolean",
    text: "Stops the rich text editor turning typed URLs into links." },
  "duplicate-responses": { value: "boolean",
    text: "Lets each possible response be used any number of times." },
  "feedback-attempts": { value: "number",
    text: "How many times the learner may press Check Answer; `0` (the default) is unlimited. Needs `instant-feedback true`." },
  "formatting-options": { value: "list of strings",
    text: "The rich text editor's toolbar buttons, e.g. `[\"bold\", \"italic\", \"unorderedList\"]`." },
  "group-possible-responses": { value: "boolean",
    text: "Sorts the possible responses into groups, each under its own heading. `bowtie` groups come from `possible-response-groups`." },
  "handwriting-recognises": { value: "string",
    text: "The math grammar set handwriting input recognises. Learnosity's default is `\"standard\"`." },
  "hints": { value: "member list",
    text: "Hints the learner can reveal, shown by `show-hints-button` (Learnosity v2025.1.LTS and later). Holds `items-list`, a list of `[content \"...\"]` entries." },
  "horizontal-layout": { value: "boolean",
    text: "Uses a compact horizontal keypad of two rows instead of the standard one — for `longtext`, its formula keypad." },
  "ignore-leading-and-trailing-spaces": { value: "boolean",
    text: "Trims the response before comparing. Learnosity's default is `true`. (Inside a scoring rule's `options`, use `ignore-leading-and-trailing-spaces-rule`.)" },
  "instant-feedback": { value: "boolean",
    text: "Adds a Check Answer button. It needs `validation` with a `valid-response` to check against, or the button marks nothing." },
  "instructor-stimulus": { value: "string",
    text: "Notes for the educator, shown above the stimulus only when the host sets Learnosity's `showInstructorStimulus` option — never to learners otherwise." },
  "is-dynamic-content": { value: "boolean",
    text: "Set by Learnosity when the question was made by its Math Question Generator. Not related to `params`; leave it unset." },
  "is-math": { value: "boolean",
    text: "Renders LaTeX in the question with MathJax. Write every backslash doubled — `\\\\frac{1}{2}`." },
  "list": { value: "list of strings",
    text: "The statements to be ordered, in the order shown. `valid-response`'s value gives their correct order as indices into this list." },
  "match-all-possible-responses": { value: "boolean",
    text: "Allows more than one valid response for a given blank. Learnosity's default is `false`." },
  "math-image-capture": { value: "boolean",
    text: "Lets the learner answer by photographing handwritten math." },
  "max-length": { value: "number",
    text: "The longest answer the learner can enter. Characters for `shorttext` (default 50) and per blank for `clozetext` (default 15 — raise it for long answers), both capped at 250; words for `longtext` and `plaintext` (default 10000)." },
  "max-response-per-cell": { value: "number",
    text: "The most responses a single cell accepts; `0` or unset is no limit." },
  "max-selection": { value: "number",
    text: "The most choices the learner may select: on `mcq` it takes effect only with `multiple-responses true`; also `token-highlight`." },
  "metadata": { value: "member list",
    text: "Question-level metadata — see [Metadata Members](#sec-Metadata-Members). The same word at item level carries the item's tags and Author Site fields." },
  "min-selection": { value: "number",
    text: "The fewest choices the learner must select. Takes effect only with `multiple-responses true`." },
  "multiple-line": { value: "boolean",
    text: "Makes each blank a multi-line text area instead of a one-line input." },
  "multiple-responses": { value: "boolean",
    text: "Turns radio buttons into checkboxes, so more than one option — per row, on `choicematrix` — may be chosen." },
  "options": { value: "list of member lists, list of strings, or member list",
    text: "For `mcq`, the choices, each `[label \"...\" value \"...\"]` — the value is what a response records and what `valid-response` names. For `choicematrix`, the column headings as strings. Inside a `clozeformula` scoring rule, a member list of [Rule Options](#sec-Rule-Options). The element types tell the three apart." },
  "placeholder": { value: "string",
    text: "Text shown in an empty response box (on `clozedropdown`, in every unselected menu). Also a `response-container` member, per box." },
  "possible-response-groups": { value: "list of member lists",
    text: "The titled source pools, each `[title \"...\" responses [\"...\", ...]]`. Answer indices count through the pools in order." },
  "possible-responses": { value: "list",
    text: "The draggable or selectable responses. A list of strings, except `clozedropdown`, which takes one list per drop-down in order of appearance." },
  "response-container": { value: "member list",
    text: "Sizing and input settings applied to every response box — see [Response Container Members](#sec-Response-Container-Members)." },
  "response-containers": { value: "list of member lists",
    text: "The same settings per response box, one entry per `{{response}}` in order." },
  "show-copy": { value: "boolean", text: "Shows a copy button in the plain text editor." },
  "show-cut": { value: "boolean", text: "Shows a cut button in the plain text editor." },
  "show-hints-button": { value: "boolean", text: "Shows the button that reveals `hints`." },
  "show-paste": { value: "boolean", text: "Shows a paste button in the plain text editor." },
  "show-word-count": { value: "boolean", text: "Shows the current word count under the text box. Learnosity's default is `true`." },
  "show-word-limit": { value: "string",
    text: "How the `max-length` word limit is shown: `\"always\"` (the default), `\"on-limit\"` (only once exceeded) or `\"off\"`." },
  "shuffle-options": { value: "boolean",
    text: "Shuffles the order of the choices, stems or entries for each learner." },
  "spellcheck": { value: "boolean", text: "Sets the input's spellcheck, autocapitalize, autocomplete and autocorrect browser attributes. Learnosity's default is `false`." },
  "stems": { value: "list of strings",
    text: "The row prompts. `valid-response`'s value has one entry per stem." },
  "stimulus": { value: "string",
    text: "The prompt the learner reads. On cloze types it sits above the `template`, and never carries a `{{response}}` blank." },
  "stimulus-review": { value: "string",
    text: "A stimulus shown only in review mode, in place of `stimulus`." },
  "submit-over-limit": { value: "boolean",
    text: "Whether the learner may save or submit once the word limit is exceeded. Learnosity's default is `false`." },
  "template": { value: "string",
    text: "The passage. On cloze types, `{{response}}` marks each blank; on `token-highlight`, each clickable token is wrapped in `<span class=\"lrn_token\">` when `tokenization` is `\"custom\"`." },
  "text-blocks": { value: "list of strings",
    text: "Character sequences the formula keypad treats as text rather than math — `\"cm\"` rather than c × m. Each at most 9 characters." },
  "tokenization": { value: "string",
    text: "How the passage is split into tokens: `\"custom\"` (the spans in `template`), `\"word\"`, `\"sentence\"` or `\"paragraph\"`." },
  "ui-style": { value: "member list",
    text: "Layout and display settings — see [Layout Members](#sec-Layout-Members)." },
  "validation": { value: "member list",
    text: "How the question is scored — see [Validation Members](#sec-Validation-Members). Write one `validation` per question: a member given twice is a compile error." },

  // -------------------------------------------------------------- validation
  "scoring-type": { group: "validation", value: "string",
    text: "`exactMatch` (the default), or a partial-scoring mode the type accepts — see [Scoring Types](#sec-Scoring-Types). An unaccepted value is a compile error." },
  "valid-response": { group: "validation", value: "member list",
    text: "The correct answer: `[score 1 value ...]`. The shape of `value` is per type, and shown in each type's section of the Function Reference." },
  "alt-responses": { group: "validation", value: "list of member lists",
    text: "Alternate correct answers, each a complete answer set covering every blank, e.g. `alt-responses [[score 1 value [\"Paree\"]]]`." },
  "allow-negative-scores": { group: "validation", value: "boolean",
    text: "Lets a `penalty` take the score below zero." },
  "penalty": { group: "validation", value: "number",
    text: "Points deducted for an incorrect response." },
  "min-score-if-attempted": { group: "validation", value: "number",
    text: "The least a learner scores for any attempt." },
  "unscored": { group: "validation", value: "boolean",
    text: "Excludes the question from scoring — a practice or survey question." },
  "automarkable": { group: "validation", value: "boolean",
    text: "Whether Learnosity scores the question automatically (the default) or it must be marked manually." },
  "enable-fullwidth-scoring": { group: "validation", value: "boolean",
    text: "Treats full-width characters (as typed in CJK input modes) as their ordinary equivalents when comparing." },
  "accent-sensitivity": { group: "validation", value: "member list",
    text: "Accepts responses whose accents differ from the answer: `accent-sensitivity [enabled true accent-penalty-points 0.5]` marks \"cafe\" correct against \"café\", less the penalty." },
  "enabled": { group: "validation", value: "boolean",
    text: "Inside `accent-sensitivity`: when `true`, accents are ignored when checking the response. Learnosity's default is `false`." },
  "accent-penalty-points": { group: "validation", value: "number",
    text: "Inside `accent-sensitivity`: points deducted when a response is accepted despite its accents differing." },
  "max-score": { group: "validation", value: "number",
    text: "The most points the question can award — for the manually scored `longtext` and `plaintext`." },
  "score-with-feedbackaide": { group: "validation", value: "boolean",
    text: "Scores the essay with Learnosity Feedback Aide, its AI scoring engine, against a rubric. A premium feature." },
  "feedbackaide-passages": { group: "validation", value: "boolean",
    text: "Includes shared passage content in the same item in Feedback Aide scoring. A premium feature." },

  // ------------------------------------------------------------------ answer
  "score": { group: "answer", value: "number",
    text: "The points the answer set is worth. When omitted, Learnosity's default applies." },
  "value": { group: "answer", value: "string, number or list",
    text: "The answer itself. Its shape is per type: option values for `mcq`, one string per blank for cloze types, one index list per row, cell or zone for grid types, and for `clozeformula` a list per blank of scoring rules, each `[method \"...\" value \"...\"]`. Never a member list — `value [score 1 value ...]` is a compile error. Also `mcq`'s option value — see `options`." },
  "matching-rule": { group: "answer", value: "string",
    text: "For `shorttext`: `\"exactMatch\"`, or `\"contains\"` to accept the answer appearing as a whole word anywhere in the response." },
  "method": { group: "answer", value: "string",
    text: "A `clozeformula` scoring rule's comparison: `equivLiteral` (the form must match), `equivSymbolic` (any equivalent expression), `equivValue` (the same value), `equivSyntax` (the shape of the answer), `stringMatch` (the characters), or a predicate taking no `value` — `isSimplified`, `isFactorised`, `isExpanded`, `isTrue` — or `isUnit`. Not checked by the compiler; an unknown method errors in Learnosity and scores 0." },

  // ------------------------------------------------------------ rule options
  "allow-decimal": { group: "rule-options", value: "boolean", text: "Allows decimal marks in the response." },
  "allow-thousands-separator": { group: "rule-options", value: "boolean", text: "Allows a thousands separator in numbers." },
  "compare-sides": { group: "rule-options", value: "boolean", text: "Compares the two sides of an equation separately rather than as a whole." },
  "decimal-places": { group: "rule-options", value: "number", text: "Significant decimal places compared by `equivValue` and `equivSymbolic` (default 10)." },
  "ignore-leading-and-trailing-spaces-rule": { group: "rule-options", value: "boolean", text: "For `stringMatch`: trims the response before comparing. Emits `ignoreLeadingAndTrailingSpaces`." },
  "ignore-order": { group: "rule-options", value: "boolean", text: "Ignores the order of terms. Documented for `equivLiteral`, but discarded by Learnosity's scorer — see C2." },
  "ignore-text": { group: "rule-options", value: "boolean", text: "Discards LaTeX `\\\\text{...}` the learner types beside the answer, so `1.23\\\\text{ cm}` still counts as a decimal." },
  "inverse-result": { group: "rule-options", value: "boolean", text: "Inverts the rule: a response that matches scores wrong." },
  "set-decimal-separator": { group: "rule-options", value: "string", text: "The character used as the decimal mark." },
  "set-thousands-separator": { group: "rule-options", value: "list of strings", text: "The characters accepted as thousands separators." },
  "syntax": { group: "rule-options", value: "string", text: "For `equivSyntax`: the form the response must take, written as a LaTeX-style command with an optional digit count — `\"\\\\number\"`, `\"\\\\integer\"`, `\"\\\\decimal3\"`, `\"\\\\scientific\"`, `\"\\\\variable\"`, `\"\\\\fraction\"`, `\"\\\\simpleFraction\"`, `\"\\\\mixedFraction\"` or `\"\\\\fractionOrDecimal\"`." },
  "treat-letters-as-variables": { group: "rule-options", value: "boolean", text: "For `equivSymbolic`: treats letters as algebraic variables." },
  "treat-multiple-spaces-as-one": { group: "rule-options", value: "boolean", text: "For `stringMatch`: collapses runs of spaces before comparing." },

  // ---------------------------------------------------------------- ui-style
  "type": { group: "ui-style", value: "string",
    text: "The widget's display variant: for `mcq` `\"horizontal\"` (the default) or `\"block\"`; for `choicematrix` `\"table\"` or `\"inline\"`; for `orderlist` `\"button\"`, `\"list\"` or `\"inline\"`; for `clozeformula` the keypad — `\"floating-keyboard\"`, `\"block-keyboard\"`, `\"block-on-focus-keyboard\"` (the default) or `\"no-input-ui\"`. The question's own `type` is emitted by the compiler, never written." },
  "fontsize": { group: "ui-style", value: "string", text: "Text size: `\"small\"`, `\"normal\"`, `\"large\"`, `\"xlarge\"` or `\"xxlarge\"`." },
  "columns": { group: "ui-style", value: "number", text: "For `mcq`: the number of columns the options are divided across (default 1)." },
  "choice-label": { group: "ui-style", value: "string", text: "For `mcq` in the `\"block\"` style: the numbering beside each option — `\"number\"`, `\"upper-alpha\"` or `\"lower-alpha\"`." },
  "orientation": { group: "ui-style", value: "string", text: "For `mcq` with several `columns`: order the options `\"vertical\"`ly (the default) or `\"horizontal\"`ly." },
  "column-count": { group: "ui-style", value: "number", text: "For `classification`: the number of columns in the grid (default 1)." },
  "column-titles": { group: "ui-style", value: "list of strings", text: "Column headings: the `classification` categories, or the `bowtie` drop zones." },
  "row-count": { group: "ui-style", value: "number", text: "For `classification`: the number of rows (default 1), for a two-dimensional grid." },
  "row-titles": { group: "ui-style", value: "list of strings", text: "For `classification`: row headings." },
  "row-header": { group: "ui-style", value: "string", text: "For `classification`: the content of the table's top-left cell." },
  "row-titles-width": { group: "ui-style", value: "string", text: "For `classification`: the width of the row-title column in pixels, e.g. `\"120px\"` (default `\"60px\"`)." },
  "row-min-height": { group: "ui-style", value: "string", text: "For `classification`: the least height of a row in pixels (default `\"60px\"`)." },
  "stem-title": { group: "ui-style", value: "string", text: "For `choicematrix`: the title of the prompt column." },
  "option-row-title": { group: "ui-style", value: "string", text: "For `choicematrix`: an extra title above the response columns." },
  "stem-width": { group: "ui-style", value: "string", text: "For `choicematrix`: the width of the prompt column in pixels, e.g. `\"120px\"`." },
  "option-width": { group: "ui-style", value: "string", text: "For `choicematrix`: the width of each response column in pixels." },
  "horizontal-lines": { group: "ui-style", value: "boolean", text: "For `choicematrix`: draws a line under each prompt row." },
  "validation-stem-numeration": { group: "ui-style", value: "string", text: "The numbering beside each validation label: `\"number\"` (the default), `\"upper-alpha\"` or `\"lower-alpha\"`." },
  "possibility-list-position": { group: "ui-style", value: "string", text: "Where the pool of draggable responses sits: `\"bottom\"` (the default), `\"top\"`, `\"left\"` or `\"right\"`." },
  "show-drag-handle": { group: "ui-style", value: "boolean", text: "Shows the indicator that responses are draggable. Learnosity's default is `true`." },
  "min-height": { group: "ui-style", value: "string", text: "For `longtext`: the least height of the text box in pixels, e.g. `\"50px\"`." },
  "max-height": { group: "ui-style", value: "string", text: "For `longtext`: the greatest height of the text box before it scrolls; unset, it grows with the text." },
  "min-width": { group: "ui-style", value: "string", text: "For `clozeformula`: the least width of the response input area, e.g. `\"550px\"`." },
  "response-font-scale": { group: "ui-style", value: "string", text: "For `clozeformula`: the response font relative to the question's — `\"boosted\"` (150%, the default) or `\"normal\"`." },
  "keyboard-below-response-area": { group: "ui-style", value: "boolean", text: "For `clozeformula`: places the floating keypad below the last line of the response area instead of partly over it." },

  // ------------------------------------------------------ response-container
  "width": { group: "response-container", value: "string", text: "The box width in pixels, e.g. `\"150px\"`." },
  "height": { group: "response-container", value: "string", text: "The box height in pixels." },
  "input-type": { group: "response-container", value: "string", text: "The kind of input the box takes. Learnosity's default is `\"text\"`." },
  "aria-label": { group: "response-container", value: "string", text: "Custom aria-label text for the box, read by screen readers." },
  "wordwrap": { group: "response-container", value: "boolean", text: "Whether a dragged response wraps inside its box or is cut off with an ellipsis. Learnosity's default is `false`." },

  // --------------------------------------------------------------- structure
  "label": { group: "structure", value: "string", text: "An `mcq` option's displayed text, beside its `value`." },
  "assistive-label": { group: "structure", value: "member list", text: "An `mcq` option's alternate label for screen readers, with `label` (plain text) and `exposed-visible-label`." },
  "exposed-visible-label": { group: "structure", value: "boolean", text: "Inside `assistive-label`: whether screen readers can navigate to the assistive label. By default it is hidden and the option's own label is read." },
  "title": { group: "structure", value: "string", text: "A `bowtie` response group's heading, shown over its column below the diagram." },
  "responses": { group: "structure", value: "list of strings", text: "A `bowtie` response group's choices." },
  "items-list": { group: "structure", value: "list of member lists", text: "Inside `hints`: the hints, in the order they are revealed, each `[content \"...\"]`. Emits `items`." },
  "content": { group: "structure", value: "string", text: "Inside a hint: the text displayed. HTML is allowed." },

  // ---------------------------------------------------------------- metadata
  "tags": { group: "metadata", emits: "`tags` (item level)", value: "record `{ Type: string | string[] }`",
    text: "Item level. Faceted tags the Author Site filters on, e.g. `tags { NGSS: \"MS-LS1-2\", DOK: 2 }`. A bare string becomes a one-element list. Difficulty and DOK labels go here — Learnosity has no dedicated field for them." },
  "notes": { group: "metadata", emits: "`note` (item level)", value: "string", text: "Item level. Emitted as the item's `note`, the Author Site's Notes field." },
  "description": { group: "metadata", value: "string", text: "Item level. Emitted as the item's `description`." },
  "source": { group: "metadata", value: "string", text: "Item level. Emitted as the item's `source`." },
  "difficulty-level": { group: "metadata", emits: "`adaptive.difficulty` (item level)", value: "integer",
    text: "Item level. Emitted as `adaptive.difficulty`, the integer calibration behind the Author Site's Difficulty level. Distinct from a `Difficulty` tag such as `\"medium\"`." },
  "distractor-rationale": { group: "metadata", value: "string", text: "Question level. Why the distractors are wrong, as one note." },
  "distractor-rationale-response-level": { group: "metadata", value: "list of strings",
    text: "Question level. One rationale per option, in order — the field the Author Site shows beside each distractor. The Questions API does not display it to learners." },
  "rubric-reference": { group: "metadata", value: "string", text: "Question level. The identifier of the rubric to mark with; defaults to the course rubric when the activity assigns one." },
  "sample-answer": { group: "metadata", value: "string", text: "Question level. A model answer, shown in the Reports API. HTML is allowed." },
  "response-shuffle-seed": { group: "metadata", value: "string", text: "Question level. A seed for shuffling the options: every learner sees the same shuffled order." },
  "acknowledgements": { group: "metadata", value: "string", text: "Question level. References for passages, documents or images the question uses." },

  // ------------------------------------------------------------------- block
  "params": { group: "block", value: "list of records", emits: "`dynamic_content_data`",
    text: "In the `items` list: the dynamic-content table, one record per row, e.g. `params [{ A1: \"50\" } { A1: \"100\" }]`. Each session draws a row and fills `{{A1}}`-style placeholders. An embedded L0179 question's own table takes precedence." },
  "save-to-itembank": { group: "block", extra: true, value: "the activity", emits: "— (the item-bank write)",
    text: "Wraps the activity to persist it: `save-to-itembank items [...] {}`. Items land as `status: \"unpublished\"`. The write runs only in a compile that selects a connection; without one the result carries `itemBank: { skipped: \"no-connection\", ... }` and the preview still renders. See [items](#sec-items)." },
  "lang": { group: "block", value: "string",
    text: "For `custom`: the deployed Graffiticode language to embed, e.g. `\"0179\"`. Required. The compiler derives `custom_type` and the script URLs from it." },
  "model": { group: "block", value: "record, string, or `data use \"<lang>\"`",
    text: "For `custom`: the embedded interaction's content, emitted unchanged as the question's `data`. Write `model data use \"0179\"` to read an upstream pipeline task." },
};
